### ISSUE TITLE
VOC units

### ISSUE THREAD

**Issue by To-Azamat** [smallwood69/homebridge-cgllc-airmonitor-s1#1]
The value of VOC that plugin reports is ppb, correct?
Cant look up the value in Homekit as the description string is too long and no actual value is visible, but Eve reports the same value in mg/m3.
Does plugin reports units of measurement or it is uo to individual apps to assign a measurement units?

**Comment by smallwood69** [comment]
The unit is correct for ppb.
The device reports in ppb.
I changed the setting to mg/m3 on the device, but it reports the same as ppb.

**Comment by To-Azamat** [comment]
Does the plugin reports plain number to HB or does it also says that the number is "ppb"?

**Comment by smallwood69** [comment]
The device sends the ppb value to the plugin and the plugin sends it to HB.
There is no place marked 'ppb' in the value received from the device.

**Comment by smallwood69** [comment]
Initially I calculated in mg/m3. However, the value displayed on the device and the value displayed on the HB were different, so it was changed to ppb.

**Comment by To-Azamat** [comment]
Ok, thank you. I get that device outputs VOC in ppb to plugin / HB and the front-end software needs to compensate for it.
Eve displaying VOC value in mg/m3 needs to do the converting on its end.

Do you see the VOC value in Homekit? What units does Homekit display?

**Comment by smallwood69** [comment]
Homekit units are still mg/m3. The unit of Homekit could not be changed to ppb.

**Comment by To-Azamat** [comment]
Ok got it. What do you think about doing ppb-2-mgm3 conversion in the plugin to report mg/m3 value to Homekit?

**Comment by smallwood69** [comment]
Homekit could not display the decimal point in mg/m3.
So, 0.011 is displayed as 0mg/m3 on the homekit screen.

**Comment by To-Azamat** [comment]
Ok. Thank you, you were most helpful.

**Comment by smallwood69** [comment]
You're welcome.
