### ISSUE TITLE
What is "token": "--------",

### ISSUE THREAD

**Issue by simoleh** [smallwood69/homebridge-cgllc-airmonitor-s1#3]
What is token and how to get it?

**Comment by i3laze** [comment]
Didn’t test, but looks like a guide to obtain a token for a Mi device:
https://sprut.ai/client/article/107

**Comment by smallwood69** [comment]
check this document.

https://github.com/Maxmudjon/com.xiaomi-miio/blob/master/docs/obtain_token.md

**Comment by voska** [comment]
@smallwood69 I tried using that document and was not able to connect. It seems the Cleargrass Air Monitor is not supported by the Mi Home app anymore. Any other ideas? 

It doesn't seem to launch a wifi server upon reset either.

**Comment by miguelpruivo** [comment]
@voska you need to use China Mainland server
