### ISSUE TITLE
Name of Co2 sensor

### ISSUE THREAD

**Issue by kitsen13** [smallwood69/homebridge-cgllc-airmonitor-s1#7]
Hello, 
I have two devices, your plugin works great;  but when I try to rename Co2 measure in homebridge the name "Co2" remains.
And in node-red, I can't rename like "Co2 chambre". 
This problem is not present with quality, temperature and humidity for example.

In node-red, only the first device is taken.

Thanks in advance,

![image](https://user-images.githubusercontent.com/3313183/136838622-2388d161-760e-4cb2-9a56-b3ee207cfbea.png)

![image](https://user-images.githubusercontent.com/3313183/136838976-b1357dd1-2e3c-46aa-a14b-2c069a71d636.png)

![image](https://user-images.githubusercontent.com/3313183/136839514-4725325e-83fa-40ff-bb23-89ffd7ea6e4b.png)

**Comment by smallwood69** [comment]
Are you saying you can't rename co2?
please add this accessories property

"accessories": [
        {
...
"showCo2": true,
**"nameCo2" : "Co2 chambre",**
"co2_Threshold": 1000          
        }
    ]

**Comment by kitsen13** [comment]
> 
> 
> Are you saying you can't rename co2? please add this accessories property
> 
> "accessories": [ { ... "showCo2": true, **"nameCo2" : "Co2 chambre",** "co2_Threshold": 1000 } ]

Great, it works !
Thanks

(soory but the read me of your plugin doesn't mention that )

**Comment by smallwood69** [comment]
Thank you.
I'll add it to the guide later.
