### ISSUE TITLE
does it work with the Qingping Air Monitor?

### ISSUE THREAD

**Issue by zsolt-dev** [smallwood69/homebridge-cgllc-airmonitor-s1#8]
Hello,

First, let me thank you for making this open source.

The xiaomi air monitor is just rebranded https://www.qingping.co/air-monitor/overview

Did anyone tried the "original" without the Mi Home account?

Thank you

**Comment by smallwood69** [comment]
This product was originally manufactured by qingping.
As long as the model code has not been changed, it can be used as is.
